## cluster analysis for the hidden layer 
rm(list=ls())

pa0=paste('C:/Users/nan/Emergent/learning networks/nan network/8Neuron3Salience_Cue_Target/trainseperately',sep='')
pa=paste(pa0,'test_results',sep='/')

result.0180=c(100)
result.updown=c(100)
result.lowmedium=c(100)
result.highmedium=c(100)
result.BRtarget=c(100)
result.TargetRed=c(100)
result.TargetBlue=c(100)
result.BRCannon=c(100)
result.EFORRed=c(100)
result.EFORBlue=c(100)

result=data.frame(result.0180,result.updown,result.lowmedium,result.highmedium, result.BRtarget=c(100),
                  result.TargetRed,result.TargetBlue,result.BRCannon,result.EFORRed,result.EFORBlue=c(100))
for (threshold in c('0.10','0.15','0.20','0.25','0.30','0.35','0.40','0.45','0.50',
                    '0.55','0.60','0.65','0.70','0.75','0.80','0.85','0.90','0.95')){
  # threshold='0.10'
  d<-read.table(paste(pa,'/','cycle10_Total Number_',threshold,'.csv',sep=''),header=TRUE,sep=",",na.string=NULL)    
  sink(paste(pa,'/cycle10_t_test',threshold,'.txt',sep=''))
  t.test(d$TargetCannon_0_Num_1,d$TargetCannon_180_Num_1)
  t.test(d$TargetCannon_Up_Num_1,d$TargetCannon_Down_Num_1)
  t.test(d$TargetCannon_salience_Low_Num_1,d$TargetCannon_salience_Medium_Num_1)
  t.test(d$TargetCannon_salience_High_Num_1,d$TargetCannon_salience_Medium_Num_1)
  t.test(d$Blue_TLoc_Num_1,d$Red_TLoc_Num_1)
  t.test(d$TLoc_Num_1,d$Red_TLoc_Num_1)
  t.test(d$TLoc_Num_1,d$Blue_TLoc_Num_1)
  t.test(d$BOri_Num_1,d$ROri_Num_1)
  t.test(d$EOri_Num,d$ROri_Num_1)
  threshold=as.numeric(threshold)
  sink()
  result.0180=t.test(d$TargetCannon_0_Num_1,d$TargetCannon_180_Num_1)
  result.updown=t.test(d$TargetCannon_Up_Num_1,d$TargetCannon_Down_Num_1)
  result.lowmedium=t.test(d$TargetCannon_salience_Low_Num_1,d$TargetCannon_salience_Medium_Num_1)
  result.highmedium=t.test(d$TargetCannon_salience_High_Num_1,d$TargetCannon_salience_Medium_Num_1)
  result.BRtarget=t.test(d$Blue_TLoc_Num_1,d$Red_TLoc_Num_1)
  result.TargetRed=t.test(d$TLoc_Num_1,d$Red_TLoc_Num_1)
  result.TargetBlue=t.test(d$TLoc_Num_1,d$Blue_TLoc_Num_1)
  result.BRCannon=t.test(d$BOri_Num_1,d$ROri_Num_1)
  result.EFORRed=t.test(d$EOri_Num,d$Red_TLoc_Num_1)
  result.EFORBlue=t.test(d$EOri_Num,d$BOri_Num_1)
  
  
  tt=c(result.0180$p.value,result.updown$p.value,
       result.lowmedium$p.value,result.highmedium$p.value,
       result.BRtarget$p.value,result.TargetRed$p.value,result.TargetBlue$p.value,
       result.BRCannon$p.value,result.EFORRed$p.value,result.EFORBlue$p.value)
  
  result[20*threshold,]=tt
}
##wirte all subjects neuron number out
write.table(result,paste(pa,'/','cycle10_t_test_result_.csv',sep=''),sep=',',col.names=NA,qmethod="double")


threshold="0.10"
d<-read.table(paste(pa,'/','cycle10_Total Number_',threshold,'.csv',sep=''),header=TRUE,sep=",",na.string=NULL)    
sink(paste(pa,'/cycle10_t_test',threshold,'.txt',sep=''))
t.test(d$TargetCannon_0_Num_1,d$TargetCannon_180_Num_1)
t.test(d$TargetCannon_Up_Num_1,d$TargetCannon_Down_Num_1)
t.test(d$TargetCannon_salience_Low_Num_1,d$TargetCannon_salience_Medium_Num_1)
t.test(d$TargetCannon_salience_High_Num_1,d$TargetCannon_salience_Medium_Num_1)
t.test(d$Blue_TLoc_Num_1,d$Red_TLoc_Num_1)
t.test(d$TLoc_Num_1,d$Red_TLoc_Num_1)
t.test(d$TLoc_Num_1,d$Blue_TLoc_Num_1)
t.test(d$BOri_Num_1,d$ROri_Num_1)
t.test(d$EOri_Num,d$ROri_Num_1)
t.test(d$EOri_Num,d$BOri_Num_1)
sink()

threshold="0.15"
d<-read.table(paste(pa,'/','cycle10_Total Number_',threshold,'.csv',sep=''),header=TRUE,sep=",",na.string=NULL)    
sink(paste(pa,'/cycle10_t_test',threshold,'.txt',sep=''))
t.test(d$TargetCannon_0_Num_1,d$TargetCannon_180_Num_1)
t.test(d$TargetCannon_Up_Num_1,d$TargetCannon_Down_Num_1)
t.test(d$TargetCannon_salience_Low_Num_1,d$TargetCannon_salience_Medium_Num_1)
t.test(d$TargetCannon_salience_High_Num_1,d$TargetCannon_salience_Medium_Num_1)
t.test(d$Blue_TLoc_Num_1,d$Red_TLoc_Num_1)
t.test(d$TLoc_Num_1,d$Red_TLoc_Num_1)
t.test(d$TLoc_Num_1,d$Blue_TLoc_Num_1)
t.test(d$BOri_Num_1,d$ROri_Num_1)
t.test(d$EOri_Num,d$ROri_Num_1)
t.test(d$EOri_Num,d$BOri_Num_1)
sink()

threshold="0.20"
d<-read.table(paste(pa,'/','cycle10_Total Number_',threshold,'.csv',sep=''),header=TRUE,sep=",",na.string=NULL)    
sink(paste(pa,'/cycle10_t_test',threshold,'.txt',sep=''))
t.test(d$TargetCannon_0_Num_1,d$TargetCannon_180_Num_1)
t.test(d$TargetCannon_Up_Num_1,d$TargetCannon_Down_Num_1)
t.test(d$TargetCannon_salience_Low_Num_1,d$TargetCannon_salience_Medium_Num_1)
t.test(d$TargetCannon_salience_High_Num_1,d$TargetCannon_salience_Medium_Num_1)
t.test(d$Blue_TLoc_Num_1,d$Red_TLoc_Num_1)
t.test(d$TLoc_Num_1,d$Red_TLoc_Num_1)
t.test(d$TLoc_Num_1,d$Blue_TLoc_Num_1)
t.test(d$BOri_Num_1,d$ROri_Num_1)
t.test(d$EOri_Num,d$ROri_Num_1)
t.test(d$EOri_Num,d$BOri_Num_1)
sink()

threshold="0.25"
d<-read.table(paste(pa,'/','cycle10_Total Number_',threshold,'.csv',sep=''),header=TRUE,sep=",",na.string=NULL)    
sink(paste(pa,'/cycle10_t_test',threshold,'.txt',sep=''))
t.test(d$TargetCannon_0_Num_1,d$TargetCannon_180_Num_1)
t.test(d$TargetCannon_Up_Num_1,d$TargetCannon_Down_Num_1)
t.test(d$TargetCannon_salience_Low_Num_1,d$TargetCannon_salience_Medium_Num_1)
t.test(d$TargetCannon_salience_High_Num_1,d$TargetCannon_salience_Medium_Num_1)
t.test(d$Blue_TLoc_Num_1,d$Red_TLoc_Num_1)
t.test(d$TLoc_Num_1,d$Red_TLoc_Num_1)
t.test(d$TLoc_Num_1,d$Blue_TLoc_Num_1)
t.test(d$BOri_Num_1,d$ROri_Num_1)
t.test(d$EOri_Num,d$ROri_Num_1)
t.test(d$EOri_Num,d$BOri_Num_1)
sink()

threshold="0.30"
d<-read.table(paste(pa,'/','cycle10_Total Number_',threshold,'.csv',sep=''),header=TRUE,sep=",",na.string=NULL)    
sink(paste(pa,'/cycle10_t_test',threshold,'.txt',sep=''))
t.test(d$TargetCannon_0_Num_1,d$TargetCannon_180_Num_1)
t.test(d$TargetCannon_Up_Num_1,d$TargetCannon_Down_Num_1)
t.test(d$TargetCannon_salience_Low_Num_1,d$TargetCannon_salience_Medium_Num_1)
t.test(d$TargetCannon_salience_High_Num_1,d$TargetCannon_salience_Medium_Num_1)
t.test(d$Blue_TLoc_Num_1,d$Red_TLoc_Num_1)
t.test(d$TLoc_Num_1,d$Red_TLoc_Num_1)
t.test(d$TLoc_Num_1,d$Blue_TLoc_Num_1)
t.test(d$BOri_Num_1,d$ROri_Num_1)
t.test(d$EOri_Num,d$ROri_Num_1)
t.test(d$EOri_Num,d$BOri_Num_1)
sink()

threshold="0.35"
d<-read.table(paste(pa,'/','cycle10_Total Number_',threshold,'.csv',sep=''),header=TRUE,sep=",",na.string=NULL)    
sink(paste(pa,'/cycle10_t_test',threshold,'.txt',sep=''))
t.test(d$TargetCannon_0_Num_1,d$TargetCannon_180_Num_1)
t.test(d$TargetCannon_Up_Num_1,d$TargetCannon_Down_Num_1)
t.test(d$TargetCannon_salience_Low_Num_1,d$TargetCannon_salience_Medium_Num_1)
t.test(d$TargetCannon_salience_High_Num_1,d$TargetCannon_salience_Medium_Num_1)
t.test(d$Blue_TLoc_Num_1,d$Red_TLoc_Num_1)
t.test(d$TLoc_Num_1,d$Red_TLoc_Num_1)
t.test(d$TLoc_Num_1,d$Blue_TLoc_Num_1)
t.test(d$BOri_Num_1,d$ROri_Num_1)
t.test(d$EOri_Num,d$ROri_Num_1)
t.test(d$EOri_Num,d$BOri_Num_1)
sink()

threshold="0.40"
d<-read.table(paste(pa,'/','cycle10_Total Number_',threshold,'.csv',sep=''),header=TRUE,sep=",",na.string=NULL)    
sink(paste(pa,'/cycle10_t_test',threshold,'.txt',sep=''))
t.test(d$TargetCannon_0_Num_1,d$TargetCannon_180_Num_1)
t.test(d$TargetCannon_Up_Num_1,d$TargetCannon_Down_Num_1)
t.test(d$TargetCannon_salience_Low_Num_1,d$TargetCannon_salience_Medium_Num_1)
t.test(d$TargetCannon_salience_High_Num_1,d$TargetCannon_salience_Medium_Num_1)
t.test(d$Blue_TLoc_Num_1,d$Red_TLoc_Num_1)
t.test(d$TLoc_Num_1,d$Red_TLoc_Num_1)
t.test(d$TLoc_Num_1,d$Blue_TLoc_Num_1)
t.test(d$BOri_Num_1,d$ROri_Num_1)
t.test(d$EOri_Num,d$ROri_Num_1)
t.test(d$EOri_Num,d$BOri_Num_1)
sink()

threshold="0.45"
d<-read.table(paste(pa,'/','cycle10_Total Number_',threshold,'.csv',sep=''),header=TRUE,sep=",",na.string=NULL)    
sink(paste(pa,'/cycle10_t_test',threshold,'.txt',sep=''))
t.test(d$TargetCannon_0_Num_1,d$TargetCannon_180_Num_1)
t.test(d$TargetCannon_Up_Num_1,d$TargetCannon_Down_Num_1)
t.test(d$TargetCannon_salience_Low_Num_1,d$TargetCannon_salience_Medium_Num_1)
t.test(d$TargetCannon_salience_High_Num_1,d$TargetCannon_salience_Medium_Num_1)
t.test(d$Blue_TLoc_Num_1,d$Red_TLoc_Num_1)
t.test(d$TLoc_Num_1,d$Red_TLoc_Num_1)
t.test(d$TLoc_Num_1,d$Blue_TLoc_Num_1)
t.test(d$BOri_Num_1,d$ROri_Num_1)
t.test(d$EOri_Num,d$ROri_Num_1)
t.test(d$EOri_Num,d$BOri_Num_1)
sink()

threshold="0.50"
d<-read.table(paste(pa,'/','cycle10_Total Number_',threshold,'.csv',sep=''),header=TRUE,sep=",",na.string=NULL)    
sink(paste(pa,'/cycle10_t_test',threshold,'.txt',sep=''))
t.test(d$TargetCannon_0_Num_1,d$TargetCannon_180_Num_1)
t.test(d$TargetCannon_Up_Num_1,d$TargetCannon_Down_Num_1)
t.test(d$TargetCannon_salience_Low_Num_1,d$TargetCannon_salience_Medium_Num_1)
t.test(d$TargetCannon_salience_High_Num_1,d$TargetCannon_salience_Medium_Num_1)
t.test(d$Blue_TLoc_Num_1,d$Red_TLoc_Num_1)
t.test(d$TLoc_Num_1,d$Red_TLoc_Num_1)
t.test(d$TLoc_Num_1,d$Blue_TLoc_Num_1)
t.test(d$BOri_Num_1,d$ROri_Num_1)
t.test(d$EOri_Num,d$ROri_Num_1)
t.test(d$EOri_Num,d$BOri_Num_1)
sink()

threshold="0.55"
d<-read.table(paste(pa,'/','cycle10_Total Number_',threshold,'.csv',sep=''),header=TRUE,sep=",",na.string=NULL)    
sink(paste(pa,'/cycle10_t_test',threshold,'.txt',sep=''))
t.test(d$TargetCannon_0_Num_1,d$TargetCannon_180_Num_1)
t.test(d$TargetCannon_Up_Num_1,d$TargetCannon_Down_Num_1)
t.test(d$TargetCannon_salience_Low_Num_1,d$TargetCannon_salience_Medium_Num_1)
t.test(d$TargetCannon_salience_High_Num_1,d$TargetCannon_salience_Medium_Num_1)
t.test(d$Blue_TLoc_Num_1,d$Red_TLoc_Num_1)
t.test(d$TLoc_Num_1,d$Red_TLoc_Num_1)
t.test(d$TLoc_Num_1,d$Blue_TLoc_Num_1)
t.test(d$BOri_Num_1,d$ROri_Num_1)
t.test(d$EOri_Num,d$ROri_Num_1)
t.test(d$EOri_Num,d$BOri_Num_1)
sink()

threshold="0.60"
d<-read.table(paste(pa,'/','cycle10_Total Number_',threshold,'.csv',sep=''),header=TRUE,sep=",",na.string=NULL)    
sink(paste(pa,'/cycle10_t_test',threshold,'.txt',sep=''))
t.test(d$TargetCannon_0_Num_1,d$TargetCannon_180_Num_1)
t.test(d$TargetCannon_Up_Num_1,d$TargetCannon_Down_Num_1)
t.test(d$TargetCannon_salience_Low_Num_1,d$TargetCannon_salience_Medium_Num_1)
t.test(d$TargetCannon_salience_High_Num_1,d$TargetCannon_salience_Medium_Num_1)
t.test(d$Blue_TLoc_Num_1,d$Red_TLoc_Num_1)
t.test(d$TLoc_Num_1,d$Red_TLoc_Num_1)
t.test(d$TLoc_Num_1,d$Blue_TLoc_Num_1)
t.test(d$BOri_Num_1,d$ROri_Num_1)
t.test(d$EOri_Num,d$ROri_Num_1)
t.test(d$EOri_Num,d$BOri_Num_1)
sink()

threshold="0.65"
d<-read.table(paste(pa,'/','cycle10_Total Number_',threshold,'.csv',sep=''),header=TRUE,sep=",",na.string=NULL)    
sink(paste(pa,'/cycle10_t_test',threshold,'.txt',sep=''))
t.test(d$TargetCannon_0_Num_1,d$TargetCannon_180_Num_1)
t.test(d$TargetCannon_Up_Num_1,d$TargetCannon_Down_Num_1)
t.test(d$TargetCannon_salience_Low_Num_1,d$TargetCannon_salience_Medium_Num_1)
t.test(d$TargetCannon_salience_High_Num_1,d$TargetCannon_salience_Medium_Num_1)
t.test(d$Blue_TLoc_Num_1,d$Red_TLoc_Num_1)
t.test(d$TLoc_Num_1,d$Red_TLoc_Num_1)
t.test(d$TLoc_Num_1,d$Blue_TLoc_Num_1)
t.test(d$BOri_Num_1,d$ROri_Num_1)
t.test(d$EOri_Num,d$ROri_Num_1)
t.test(d$EOri_Num,d$BOri_Num_1)
sink()

threshold="0.70"
d<-read.table(paste(pa,'/','cycle10_Total Number_',threshold,'.csv',sep=''),header=TRUE,sep=",",na.string=NULL)    
sink(paste(pa,'/cycle10_t_test',threshold,'.txt',sep=''))
t.test(d$TargetCannon_0_Num_1,d$TargetCannon_180_Num_1)
t.test(d$TargetCannon_Up_Num_1,d$TargetCannon_Down_Num_1)
t.test(d$TargetCannon_salience_Low_Num_1,d$TargetCannon_salience_Medium_Num_1)
t.test(d$TargetCannon_salience_High_Num_1,d$TargetCannon_salience_Medium_Num_1)
t.test(d$Blue_TLoc_Num_1,d$Red_TLoc_Num_1)
t.test(d$TLoc_Num_1,d$Red_TLoc_Num_1)
t.test(d$TLoc_Num_1,d$Blue_TLoc_Num_1)
t.test(d$BOri_Num_1,d$ROri_Num_1)
t.test(d$EOri_Num,d$ROri_Num_1)
t.test(d$EOri_Num,d$BOri_Num_1)
sink()

threshold="0.75"
d<-read.table(paste(pa,'/','cycle10_Total Number_',threshold,'.csv',sep=''),header=TRUE,sep=",",na.string=NULL)    
sink(paste(pa,'/cycle10_t_test',threshold,'.txt',sep=''))
t.test(d$TargetCannon_0_Num_1,d$TargetCannon_180_Num_1)
t.test(d$TargetCannon_Up_Num_1,d$TargetCannon_Down_Num_1)
t.test(d$TargetCannon_salience_Low_Num_1,d$TargetCannon_salience_Medium_Num_1)
t.test(d$TargetCannon_salience_High_Num_1,d$TargetCannon_salience_Medium_Num_1)
t.test(d$Blue_TLoc_Num_1,d$Red_TLoc_Num_1)
t.test(d$TLoc_Num_1,d$Red_TLoc_Num_1)
t.test(d$TLoc_Num_1,d$Blue_TLoc_Num_1)
t.test(d$BOri_Num_1,d$ROri_Num_1)
t.test(d$EOri_Num,d$ROri_Num_1)
t.test(d$EOri_Num,d$BOri_Num_1)
sink()

threshold="0.80"
d<-read.table(paste(pa,'/','cycle10_Total Number_',threshold,'.csv',sep=''),header=TRUE,sep=",",na.string=NULL)    
sink(paste(pa,'/cycle10_t_test',threshold,'.txt',sep=''))
t.test(d$TargetCannon_0_Num_1,d$TargetCannon_180_Num_1)
t.test(d$TargetCannon_Up_Num_1,d$TargetCannon_Down_Num_1)
t.test(d$TargetCannon_salience_Low_Num_1,d$TargetCannon_salience_Medium_Num_1)
t.test(d$TargetCannon_salience_High_Num_1,d$TargetCannon_salience_Medium_Num_1)
t.test(d$Blue_TLoc_Num_1,d$Red_TLoc_Num_1)
t.test(d$TLoc_Num_1,d$Red_TLoc_Num_1)
t.test(d$TLoc_Num_1,d$Blue_TLoc_Num_1)
t.test(d$BOri_Num_1,d$ROri_Num_1)
t.test(d$EOri_Num,d$ROri_Num_1)
t.test(d$EOri_Num,d$BOri_Num_1)
sink()

threshold="0.85"
d<-read.table(paste(pa,'/','cycle10_Total Number_',threshold,'.csv',sep=''),header=TRUE,sep=",",na.string=NULL)    
sink(paste(pa,'/cycle10_t_test',threshold,'.txt',sep=''))
t.test(d$TargetCannon_0_Num_1,d$TargetCannon_180_Num_1)
t.test(d$TargetCannon_Up_Num_1,d$TargetCannon_Down_Num_1)
t.test(d$TargetCannon_salience_Low_Num_1,d$TargetCannon_salience_Medium_Num_1)
t.test(d$TargetCannon_salience_High_Num_1,d$TargetCannon_salience_Medium_Num_1)
t.test(d$Blue_TLoc_Num_1,d$Red_TLoc_Num_1)
t.test(d$TLoc_Num_1,d$Red_TLoc_Num_1)
t.test(d$TLoc_Num_1,d$Blue_TLoc_Num_1)
t.test(d$BOri_Num_1,d$ROri_Num_1)
t.test(d$EOri_Num,d$ROri_Num_1)
t.test(d$EOri_Num,d$BOri_Num_1)
sink()

threshold="0.90"
d<-read.table(paste(pa,'/','cycle10_Total Number_',threshold,'.csv',sep=''),header=TRUE,sep=",",na.string=NULL)    
sink(paste(pa,'/cycle10_t_test',threshold,'.txt',sep=''))
t.test(d$TargetCannon_0_Num_1,d$TargetCannon_180_Num_1)
t.test(d$TargetCannon_Up_Num_1,d$TargetCannon_Down_Num_1)
t.test(d$TargetCannon_salience_Low_Num_1,d$TargetCannon_salience_Medium_Num_1)
t.test(d$TargetCannon_salience_High_Num_1,d$TargetCannon_salience_Medium_Num_1)
t.test(d$Blue_TLoc_Num_1,d$Red_TLoc_Num_1)
t.test(d$TLoc_Num_1,d$Red_TLoc_Num_1)
t.test(d$TLoc_Num_1,d$Blue_TLoc_Num_1)
t.test(d$BOri_Num_1,d$ROri_Num_1)
t.test(d$EOri_Num,d$ROri_Num_1)
t.test(d$EOri_Num,d$BOri_Num_1)
sink()

threshold="0.95"
d<-read.table(paste(pa,'/','cycle10_Total Number_',threshold,'.csv',sep=''),header=TRUE,sep=",",na.string=NULL)    
sink(paste(pa,'/cycle10_t_test',threshold,'.txt',sep=''))
t.test(d$TargetCannon_0_Num_1,d$TargetCannon_180_Num_1)
t.test(d$TargetCannon_Up_Num_1,d$TargetCannon_Down_Num_1)
t.test(d$TargetCannon_salience_Low_Num_1,d$TargetCannon_salience_Medium_Num_1)
t.test(d$TargetCannon_salience_High_Num_1,d$TargetCannon_salience_Medium_Num_1)
t.test(d$Blue_TLoc_Num_1,d$Red_TLoc_Num_1)
t.test(d$TLoc_Num_1,d$Red_TLoc_Num_1)
t.test(d$TLoc_Num_1,d$Blue_TLoc_Num_1)
t.test(d$BOri_Num_1,d$ROri_Num_1)
t.test(d$EOri_Num,d$ROri_Num_1)
t.test(d$EOri_Num,d$BOri_Num_1)
sink()


